### PR TITLE
Apply "gofmt" and fix names of params passed to "gosdc"

### PR DESCRIPTION
**Pull request by tianon**

### CODE REVIEW

**Comment by tianon** [comment]
Didn't notice this in #1 :sweat_smile:

**Comment by misterbisson** [comment]
🏡 🚶

**Comment by tianon** [comment]
Maybe someday later we can revert this commit when you deprecate `gosdc` in favor of `gotriton` :smile:

**Comment by tianon** [comment]
(merged this since we don't even compile ATM without it :innocent:)

**Pull request merged**
